#CNN construction and training

#import required libraries 
import os 
import numpy as np 
from numpy.random import permutation
import tensorflow as tf
from tensorflow import keras
import tensorflow.keras 
from tensorflow.keras.models import Sequential, Model
import tensorflow.keras.layers
from keras import backend as K
import keras.backend as K
from  matplotlib import pyplot as plt
import matplotlib.image as mpimg
import cv2 
import pickle as pickle

#load dataset (images) from files; data are expected to be stored in two separate folders, each containing all images belonging to the same class
#input: file-path to folders containing the data
#output: list of images
#        list of class_names
def create_dataset(path):
	img_data_array=[]
	class_name=[]
	
	for directory in [name for name in os.listdir(path) if os.path.isdir(os.path.join(path, name))]:
		for file in os.listdir(os.path.join(path, directory)):
			if not os.path.isdir(file) and not "check" in file: #exclude folders and data automatically generated by JupyterLab
				image_path = os.path.join(path, directory, file)
				image = mpimg.imread(image_path)
				image = np.array(image)
				image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) #reduce image to one channel (gray)
				image = image.astype('float32')
				img_data_array.append(image)
				class_name.append(directory)
	return img_data_array, class_name 


#calculate the error estimate
#input: list of true values
#       list of predicted values
#output: cacluated error
def error_estimate(y_true, y_pred): 
	y_pred = tf.keras.backend.clip(y_pred, 0, 1) #make sure all values are between 0 and 1
	y_pred = tf.keras.backend.round(y_pred) #round values in the prediction
	pgt = tf.greater(y_pred, y_true) #prediction value greater true value
	pgt = tf.keras.backend.cast(pgt, 'float32') #cast bool to float
	tgp = tf.greater(y_true, y_pred) #true value greater prediction value
	tgp = tf.keras.backend.cast(tgp, 'float32') #cast bool to float
	
	s = tf.reduce_sum(pgt, axis=-1) + tf.reduce_sum(tgp, axis=-1) #count how often prediction was greater true plus how often true was greater prediction (i.e., count wrong predictions)
	
	#return s / K.int_shape(y_pred)[-1] #divide by the number of elements in the tensor's last dimension
	return s / tf.cast(y_pred.shape[-1], tf.float32)

#create a keras neural network model
#input: number of CNNs (t)
#       number of filters in the CNNs
#       number of convolutional / hidden layers (Ln) 
#       level of the network (l)
#       and the neurons in the hidden layers 
#output: keras model
def create_model(t, filter_count, Ln, l, neurons): 
	IMG_HEIGHT = 32
	IMG_WIDTH = 32
	
	#loss_function to be used for training the neural network is set to Mean Squared Error (mse)
	loss_function = 'mse'
	
	#empty list for layers to be stored
	flat = []
	layers = [[]]
	fcff_layers = []
	inputs = []
	
	#convolutional neural network(s)
	for k in range(t): 
		layers.append([]) #append a new empty array to layers (for the second dimension)
		#input-layer: input_shpe = 32x32x1 (32 x 32 pixel with one gray scale value per pixel)
		layers[k].append(tf.keras.layers.Input(shape=(IMG_HEIGHT, IMG_WIDTH, 1))) 
		inputs.append(layers[k][-1]) #safe the input-layers separatly for the model creation
		
		#construct convolutional layers
		#number of layers: l * L_n
		for i in range(1, l+1):
			#calculate filter_size (2^1 in the frist L_n layers, 2^2 in the second L_n layers, ... , 2^l in the l-th L_n layers)
			kernel_size = 2 ** i 
			for j in range(Ln):
				#add a one-sided zero-padding to the input of the next convolutional layer, such that the size of the feature-map stays the same (i.e., adding padding of size kernel_size-1)
				layers[k].append(tf.keras.layers.ZeroPadding2D(((0, kernel_size-1), (0, kernel_size-1)))(layers[k][-1])) 
				#adding convutional layers, with k^(1) many filters, kernel size (from 2^1 ... 2^l), stride = 1, activation-function 'relu' and using a bias.
				layers[k].append(tf.keras.layers.Conv2D(filters = filter_count, kernel_size = kernel_size, strides = 1, padding = 'valid', activation = 'relu', use_bias=True, kernel_initializer="glorot_uniform", bias_initializer="zeros", name='ConvLayer_'+str(k)+'_'+str(i)+'-'+str(j)+'_'+str(kernel_size))(layers[k][-1])) 
		
		#output weigth as a convolutional layer with filter-size 1, i.e., the filter is a single number which is multiplied with each element of a channel's feature-map, and the channels are added element-wise
		layers[k].append(tf.keras.layers.Conv2D(filters = 1, kernel_size = 1, strides = 1, padding = 'valid', activation = 'linear', use_bias=False, name='LinearLayer_multiplcation_'+str(k))(layers[k][-1])) 
		
		#max-pooling of the linear layer's output. The pool_size equals to the image dimensions minus filter-size of the last convutional layer plus one
		layers[k].append(tf.keras.layers.MaxPool2D(pool_size = IMG_HEIGHT - kernel_size + 1, strides = None, name="MaxPool_"+str(k))(layers[k][-1])) # pool_size = filter_size of last convutional layer 
		
		#flatten the network to pass it to the concatenation layer and afterwards to the fully connected neural network
		flat.append(tf.keras.layers.Flatten()(layers[k][len(layers[k])-1])) 
	
	#concatenate CNN-outputs if there is more than one CNN 
	if(len(flat) > 1):
		fcff_layers.append(tf.keras.layers.concatenate(flat)) 
	else:
		fcff_layers.append(flat[0])
	
	#fully connected multilayer feedforward neural network
	
	#create L_n many layers with k^(2) many neurons per layer
	for j in range(Ln):
		fcff_layers.append(tf.keras.layers.Dense(units = neurons, use_bias = True, kernel_initializer='random_normal', bias_initializer='zeros', activation = 'relu')(fcff_layers[-1])) 
	
	#output layer, with only one neuron producing a prediction of the image's class
	outputs = tf.keras.layers.Dense(units = 1, use_bias = True, activation = 'linear')(fcff_layers[-1]) 
	
	#create a keras model from the layers created above
	model = tf.keras.Model(inputs=inputs, outputs=outputs)
	#use the Adam-optimizer
	opt = tf.keras.optimizers.Adam()
	model.compile(optimizer=opt, loss=loss_function, metrics=[error_estimate]) 
	
	return model


#calculate the number of trainable parameters in a model
#input: a keras model
#output: number of trainable parameters in the given model
def trainable_params_count(model):
	#trainable_count = np.sum([K.count_params(w) for w in model.trainable_weights])
	#return trainable_count	
    return model.count_params()




#program start 

#create folders
if not os.path.exists('models'):
	os.makedirs('models')
if not os.path.exists('history'):
	os.makedirs('history')

#load images and their classes from the specified path. 
images, class_name = create_dataset(r'3obj-images') 

#convert data to match input format of the neural network, store the images in variable data_X
data_X = np.array(images, np.float32) 
data_X = np.expand_dims(data_X, axis=3) #make each gray-scale value an array, to meet input format expectation of keras


#convert class names into numbers and store the list of classes in variable data_y
class_dict = {k: v for v, k in enumerate(np.unique(class_name))} 
data_y = [class_dict[class_name[i]] for i in range(len(class_name))]
data_y = np.array(data_y, np.float32) #convert labels to np-array of type float32, to meet input format expectation of keras


#permute the input data
perm = permutation(len(data_X)) 
data_X = data_X[perm]
data_y = data_y[perm]


#set the validation split, use 80% of data for training and 20% for validation
validation_split = 0.2 


#set list of value to select from for every hyperparameter
t = [1, 2] # t \in {1,2} 
k1 = [2, 4, 8] # k^(1) \in {2, 4, 8}
Ln = [1, 2, 3] #L_n \in {1, 2, 3}
l = [2, 3, 4] # l \in {2, 3, 4}
k2 = [5, 10] # k^2 \in {5, 10}


x = [] #for multi-headed networks the input data must be provided as list (of images)

#iterate over all possible hyperparameter combinations 
for ti in t: 
	x.append(data_X) #repeat data t times in a list as input for a model with t heads
	for k1i in k1:
		for Lni in Ln:
			for li in l:
				for k2i in k2:
					#create a neural network model for the hyperparameters
					model = create_model(t = ti, filter_count = k1i, Ln = Lni, l = li, neurons = k2i) 
					#check if the number of trainable parameters of the model is larger than the number of input samples. If its larger it is skipped
					if(trainable_params_count(model) > len(data_X)*(1.0-validation_split)): 
						print("too many trainable parameters ("+str(trainable_params_count(model))+") for t="+str(ti)+", k1="+str(k1i)+", Ln="+str(Lni)+", l="+str(li)+", k2="+str(k2i)+"! skipping")
					#if the number of trainable parameters it not too large the model is trained
					else:
						print("Running parameter-set t="+str(ti)+", k1="+str(k1i)+", Ln="+str(Lni)+", l="+str(li)+", k2="+str(k2i)+" ("+str(trainable_params_count(model))+" trainable parameters)")
						#train the model
						history = model.fit(x = x, y = data_y, epochs = 2000, validation_split=validation_split) 
						#save trained parameters of the model
						model.save_weights("models/"+str(ti)+"_"+str(k1i)+"_"+str(Lni)+"_"+str(li)+"_"+str(k2i)+".weights.h5")
						#saving validation results
						np.save("history/"+str(ti)+"_"+str(k1i)+"_"+str(Lni)+"_"+str(li)+"_"+str(k2i), history.history)
